### PR TITLE
starting configuration for flake8 ignoring every failure

### PR DESCRIPTION
**Pull request by szabgab**
IMHO it would be better if code aimed at beginners would adhere to the style-guides of flake8 and pylint. This PR will set up the skeleton for verifying this. If you merge it then you'll be able to clean up the code step-by-step.

### CODE REVIEW

**Comment by Aatmaj-Zephyr** [comment]
Thanks a lot for this. 

I aim to present this course on various other platforms including paid ones. Maybe attempt an ebook for the same.
However, I was just wondering if your contributions will affect any Copywrite issues?

**Review by Aatmaj-Zephyr — COMMENTED** [review]
Looks like actions is used. Alien to me. But as long as code looks indented, it is just fine.

**Comment by szabgab** [comment]
See this blog post where I started to explain this: https://code-maven.com/flake8

**Comment by Aatmaj-Zephyr** [comment]
Thanks a lot for your help. 
But upon reconsideration, I feel that I would rather manually edit code whenever I will require to repost it on other platforms. This is because this won't fix the code presented in the markdown.
Once again, thanks a lot for your kind efforts.

**Comment by szabgab** [comment]
This does not automatically change the code. This just checks if certain rules are followed in the code. Then you decide if you want to follow the rule or ignore it.

**Comment by Aatmaj-Zephyr** [comment]
Thanks. Your initiative is excellent!
I would recommend you to try your code on this repository
https://github.com/Rishit-dagli/Python3-by-practice
This is a similar project and I am sure your idea will be welcome over there.

**Comment by Aatmaj-Zephyr** [comment]
Sir you might find this useful https://dev.to/mritunjay394/how-to-automate-code-formatting-for-python-projects-with-github-actions-a-study-47g8

**Pull request closed without merging**
